### ISSUE TITLE
Update to `ember-modifier` v4

### ISSUE THREAD

**Issue by boris-petrov** [jelhan/ember-style-modifier#132]
`ember-modifier` v4 is [out](https://github.com/ember-modifier/ember-modifier/releases/tag/v4.0.0). It would be nice to update `ember-style-modifier` to use/support it.

**Comment by jelhan** [comment]
A pull request, which widens the version range for `ember-modifier` is highly welcome. It should support v3 and v4 in parallel to avoid causing a dependency hell for all the direct and indirect consumers of this addon.

I haven't reviewed changes in `ember-modifier` v4 yet. Not sure if we need having different code paths for v3 and v4. If so, `@embroider/macros` would be my preferred choice for implementing them.

A PR should additionally add test coverage to ensure that `ember-style-modifier` supports both `ember-modifier` v3 and v4.

**Comment by jelhan** [comment]
Support for ember-modifier@v4 has been implemented in #133 by @SergeAstapov and relased as [v2.0.0](https://github.com/jelhan/ember-style-modifier/releases/tag/v2.0.0). It is a breaking change because ember-modifier@v4 required ember-auto-import@v2 and I have missed to add that dependency before releasing ember-style-modifier@1.0.0. Addons having a dependency on ember-style-modifier should widen the version range to support both `^1.0.0 || ^2.0.0` in parallel rather than forcing an upgrade.

Thanks a lot to @SergeAstapov for working on it!
